use super::pool::{open_memory,open_pool,SqlitePool};use crate::types::{Note,NoteData};use crate::Result;use rusqlite::{params,OptionalExtension,Row};use std::path::Path;use std::time::{SystemTime,UNIX_EPOCH};
#[derive(Debug,Clone)]pub struct NotesStore{pool:SqlitePool}
impl NotesStore{pub fn open(path:impl AsRef<Path>)->Result<Self>{Ok(Self{pool:open_pool(path.as_ref())?})}pub fn in_memory()->Result<Self>{Ok(Self{pool:open_memory()?})}pub fn pool_max_size(&self)->u32{self.pool.max_size()}
pub fn get_notes_list(&self,q:Option<&str>)->Result<Vec<Note>>{let c=self.pool.get()?;let mut out=Vec::new();if let Some(q)=q.filter(|q|!q.trim().is_empty()){let p=format!("%{}%",q.trim());let mut s=c.prepare("SELECT id,title,content,highlights_json,list_structure_json,pinned,created_at,modified_at FROM notes WHERE title LIKE ?1 COLLATE NOCASE OR content LIKE ?1 COLLATE NOCASE ORDER BY pinned DESC,modified_at DESC,id DESC")?;for row in s.query_map(params![p],raw)?{out.push(row?.into_note()?)} }else{let mut s=c.prepare("SELECT id,title,content,highlights_json,list_structure_json,pinned,created_at,modified_at FROM notes ORDER BY pinned DESC,modified_at DESC,id DESC")?;for row in s.query_map([],raw)?{out.push(row?.into_note()?)} }Ok(out)}
pub fn get_note(&self,id:i64)->Result<Option<Note>>{let c=self.pool.get()?;c.query_row("SELECT id,title,content,highlights_json,list_structure_json,pinned,created_at,modified_at FROM notes WHERE id=?1",params![id],raw).optional()?.map(Raw::into_note).transpose()}
pub fn save_note(&self,n:&NoteData)->Result<i64>{let mut c=self.pool.get()?;let tx=c.transaction()?;let now=now();let h=serde_json::to_string(&n.highlights)?;let l=serde_json::to_string(&n.list_structure)?;let id=if n.id>0{let id=n.id;let changed=tx.execute("UPDATE notes SET title=?1,content=?2,highlights_json=?3,list_structure_json=?4,pinned=?5,modified_at=?6 WHERE id=?7",params![n.title,n.content,h,l,i64::from(n.pinned),now,id])?;if changed==0{tx.execute("INSERT INTO notes(id,title,content,highlights_json,list_structure_json,pinned,created_at,modified_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?7)",params![id,n.title,n.content,h,l,i64::from(n.pinned),now])?;}id}else{tx.execute("INSERT INTO notes(title,content,highlights_json,list_structure_json,pinned,created_at,modified_at) VALUES(?1,?2,?3,?4,?5,?6,?6)",params![n.title,n.content,h,l,i64::from(n.pinned),now])?;tx.last_insert_rowid()};tx.commit()?;Ok(id)}
pub fn delete_note(&self,id:i64)->Result<()>{let c=self.pool.get()?;c.execute("DELETE FROM notes WHERE id=?1",params![id])?;Ok(())}
pub fn toggle_pin(&self,id:i64)->Result<bool>{let c=self.pool.get()?;let old:Option<i64>=c.query_row("SELECT pinned FROM notes WHERE id=?1",params![id],|r|r.get(0)).optional()?;let pinned=match old{Some(v)=>v==0,None=>return Err(crate::CoreError::InvalidValue(format!("note {id} does not exist")))};c.execute("UPDATE notes SET pinned=?1,modified_at=?2 WHERE id=?3",params![i64::from(pinned),now(),id])?;Ok(pinned)}}
#[derive(Debug)]struct Raw{id:i64,title:String,content:String,highlights:String,lists:String,pinned:i64,created:i64,modified:i64}
impl Raw{fn into_note(self)->Result<Note>{Ok(Note{id:self.id,title:self.title,content:self.content,highlights:serde_json::from_str(&self.highlights).unwrap_or_default(),list_structure:serde_json::from_str(&self.lists).unwrap_or_default(),pinned:self.pinned!=0,created_at:self.created,modified_at:self.modified})}}
fn raw(r:&Row<'_>)->rusqlite::Result<Raw>{Ok(Raw{id:r.get(0)?,title:r.get(1)?,content:r.get(2)?,highlights:r.get(3)?,lists:r.get(4)?,pinned:r.get(5)?,created:r.get(6)?,modified:r.get(7)?})}fn now()->i64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs() as i64}
