#[cfg(windows)]use super::ffi;
#[cfg(windows)]use super::wrapper::DirectEditor;
use std::ffi::c_void;
#[derive(Debug)]pub enum EmbedError{UnsupportedPlatform,NativeCallFailed(String)}impl std::fmt::Display for EmbedError{fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{match self{Self::UnsupportedPlatform=>f.write_str("Scintilla embedding unavailable on this backend"),Self::NativeCallFailed(s)=>f.write_str(s)}}}impl std::error::Error for EmbedError{}
#[cfg(windows)]pub struct ScintillaHost{hwnd:*mut c_void,direct:DirectEditor}
#[cfg(not(windows))]pub struct ScintillaHost;
#[cfg(windows)]impl ScintillaHost{pub fn attach(parent:*mut c_void,x:i32,y:i32,w:i32,h:i32)->Result<Self,EmbedError>{let instance=unsafe{GetModuleHandleW(std::ptr::null())};if instance.is_null(){return Err(EmbedError::NativeCallFailed("GetModuleHandleW failed".into()))}if !unsafe{Scintilla_RegisterClasses(instance)}{return Err(EmbedError::NativeCallFailed("Scintilla_RegisterClasses failed".into()))}let class=wide("Scintilla");let hwnd=unsafe{CreateWindowExW(0,class.as_ptr(),wide("").as_ptr(),0x40000000|0x10000000|0x02000000|0x04000000,x,y,w,h,parent,std::ptr::null_mut(),instance,std::ptr::null_mut())};if hwnd.is_null(){return Err(EmbedError::NativeCallFailed("CreateWindowExW failed".into()))}let f=unsafe{SendMessageW(hwnd,ffi::SCI_GETDIRECTFUNCTION,0,0)};let p=unsafe{SendMessageW(hwnd,ffi::SCI_GETDIRECTPOINTER,0,0)};let direct=unsafe{DirectEditor::from_raw(f,p)}.ok_or_else(||EmbedError::NativeCallFailed("Scintilla direct calls unavailable".into()))?;Ok(Self{hwnd,direct})}pub fn direct(&self)->&DirectEditor{&self.direct}pub fn resize(&self,x:i32,y:i32,w:i32,h:i32){unsafe{SetWindowPos(self.hwnd,std::ptr::null_mut(),x,y,w,h,0x14);}}}
#[cfg(windows)]impl Drop for ScintillaHost{fn drop(&mut self){unsafe{DestroyWindow(self.hwnd);Scintilla_ReleaseResources();}}}
#[cfg(not(windows))]impl ScintillaHost{pub fn attach(_: *mut c_void,_:i32,_:i32,_:i32,_:i32)->Result<Self,EmbedError>{Err(EmbedError::UnsupportedPlatform)}}
#[cfg(windows)]extern "system"{fn CreateWindowExW(u32,*const u16,*const u16,u32,i32,i32,i32,i32,*mut c_void,*mut c_void,*mut c_void,*mut c_void)->*mut c_void;fn SendMessageW(*mut c_void,u32,usize,isize)->isize;fn SetWindowPos(*mut c_void,*mut c_void,i32,i32,i32,i32,u32)->i32;fn DestroyWindow(*mut c_void)->i32;fn GetModuleHandleW(*const u16)->*mut c_void;}
#[cfg(windows)]extern "C"{fn Scintilla_RegisterClasses(instance:*mut c_void)->bool;fn Scintilla_ReleaseResources()->bool;}
#[cfg(windows)]fn wide(s:&str)->Vec<u16>{s.encode_utf16().chain(std::iter::once(0)).collect()}
