use crate::controller::EditorSnapshot;
use crate::layout::{Layout,Rect};
use crate::theme::{Rgba,Theme};
use crate::ui::{self,FindBarState};
use fontdue::{Font,FontSettings};
use notepad_core::{LineColour,Note,ListType};
use std::path::Path;
use std::time::Instant;
use tiny_skia::{Color,FillRule,PathBuilder,Pixmap,Transform};

pub struct ChromeRenderer{font:Option<Font>,font_size:f32,started:Instant}
impl Default for ChromeRenderer{fn default()->Self{Self::new()}}
impl ChromeRenderer{pub fn new()->Self{Self{font:load_font(),font_size:15.,started:Instant::now()}}pub fn set_font_size(&mut self,s:f32){self.font_size=s.clamp(8.,96.)}pub fn render(&mut self,w:u32,h:u32,l:Layout,t:Theme,snapshot:Option<&EditorSnapshot>,tabs:&[(String,bool)],notes:&[Note],find:&FindBarState,show_line_numbers:bool,active_tab:usize)->Option<Pixmap>{let mut p=Pixmap::new(w.max(1),h.max(1))?;fill_rect(&mut p,Rect::new(0,0,w as i32,h as i32),t.window_bg);self.background(&mut p,w,h,t);self.title(&mut p,l,t);self.tabs(&mut p,l,t,tabs,active_tab);self.toolbar(&mut p,l,t);if find.open{self.find(&mut p,l,t,find)}self.sidebar(&mut p,l,t,notes);self.editor(&mut p,l,t,snapshot,show_line_numbers);self.status(&mut p,l,t,snapshot);Some(p)}
fn background(&self,p:&mut Pixmap,w:u32,h:u32,t:Theme){for(i,(x,y,r))in[(.72,.46,360.),(.18,.72,290.),(.88,.88,210.)].into_iter().enumerate(){let time=self.started.elapsed().as_secs_f32();let x=w as f32*x+time.sin()*(r*.05);let y=h as f32*y+(time*.8).cos()*(r*.04);fill_circle(p,x,y,r,if i%2==0{t.accent.with_alpha(10)}else{t.accent_alt.with_alpha(8)})}}
fn title(&self,p:&mut Pixmap,l:Layout,t:Theme){fill_rect(p,l.titlebar,t.surface);self.text(p,16,21,"NotePad Pro",t.text,15.);self.text(p,118,20,"1.0.2",t.muted_text,11.);let(a,b,c)=l.titlebar_button_rects();fill_rect(p,a,t.surface_alt.with_alpha(80));fill_rect(p,b,t.surface_alt.with_alpha(80));fill_rect(p,c,t.accent.with_alpha(24));self.text(p,a.x+18,21,"—",t.text,14.);self.text(p,b.x+17,21,"□",t.text,12.);self.text(p,c.x+18,21,"×",t.text,15.)}
fn tabs(&self,p:&mut Pixmap,l:Layout,t:Theme,tabs:&[(String,bool)],active_tab:usize){fill_rect(p,l.tab_bar,t.editor_bg);for(i,v)in ui::tab_bar::layout_tabs(l,tabs).iter().enumerate(){fill_rect(p,v.rect,if i==active_tab{t.surface}else{t.surface.with_alpha(90)});let title=if v.dirty{format!("{} •",v.title)}else{v.title.clone()};self.text(p,v.rect.x+12,v.rect.y+18,&title,if i==active_tab{t.text}else{t.muted_text},12.)}self.text(p,l.tab_bar.right()-34,l.tab_bar.y+24,"+",t.accent,20.)}
fn toolbar(&self,p:&mut Pixmap,l:Layout,t:Theme){fill_rect(p,l.toolbar,t.surface.with_alpha(220));for(b,a)in ui::toolbar::buttons(l){if let ui::toolbar::ToolbarAction::Highlight(c)=a{fill_rect(p,b.rect,colour(c))}else{fill_rect(p,b.rect,t.surface);self.text(p,b.rect.x+10,b.rect.y+18,&b.label,t.text,11.)}}}
fn find(&self,p:&mut Pixmap,l:Layout,t:Theme,f:&FindBarState){fill_rect(p,l.find_bar,t.surface_alt);fill_rect(p,Rect::new(12,l.find_bar.y+6,280,26),t.editor_bg);self.text(p,22,l.find_bar.y+23,if f.query.is_empty(){"Find…"}else{&f.query},if f.query.is_empty(){t.muted_text}else{t.text},12.);self.text(p,306,l.find_bar.y+23,&f.counter(),t.muted_text,11.)}
fn sidebar(&self,p:&mut Pixmap,l:Layout,t:Theme,notes:&[Note]){if !l.sidebar_open{return}fill_rect(p,l.sidebar,t.surface);self.text(p,16,l.sidebar.y+25,"Notes",t.text,16.);fill_rect(p,Rect::new(12,l.sidebar.y+34,l.sidebar.w-24,26),t.editor_bg);self.text(p,22,l.sidebar.y+52,"Search notes…",t.muted_text,11.);for(i,n)in notes.iter().take(8).enumerate(){let r=Rect::new(12,l.sidebar.y+54+i as i32*68,l.sidebar.w-24,58);fill_rect(p,r,if n.pinned{t.accent.with_alpha(28)}else{t.surface_alt.with_alpha(120)});self.text(p,r.x+10,r.y+21,if n.title.is_empty(){"Untitled"}else{&n.title},t.text,11.);self.text(p,r.x+10,r.y+41,n.content.lines().next().unwrap_or(""),t.muted_text,10.)}}
fn editor(&self,p:&mut Pixmap,l:Layout,t:Theme,s:Option<&EditorSnapshot>,show_line_numbers:bool){fill_rect(p,l.editor,t.editor_bg);let Some(s)=s else{return};let lines:Vec<&str>=s.text.split('\n').collect();let lh=(self.font_size*1.55).ceil()as i32;let margin=if show_line_numbers{Layout::line_number_width(lines.len(),(self.font_size*.62)as i32)}else{0};if show_line_numbers{fill_rect(p,Rect::new(l.editor.x,l.editor.y,margin,l.editor.h),t.surface.with_alpha(100));}let cursor_line=s.text[..s.cursor.min(s.text.len())].bytes().filter(|b|*b==b'\n').count();for(i,line)in lines.iter().enumerate().take(((l.editor.h-18).max(0)/lh.max(1))as usize+1){let base=l.editor.y+22+i as i32*lh;if i==cursor_line{fill_rect(p,Rect::new(l.editor.x+margin,base-lh+4,l.editor.w-margin,lh),t.accent.with_alpha(14))}if let Some(m)=s.metadata.get(i){if m.colour!=LineColour::None{fill_rect(p,Rect::new(l.editor.x+margin,base-lh+4,l.editor.w-margin,lh),colour(m.colour).with_alpha(45))}let mark=match m.list_type{ListType::Bullet=>"•",ListType::Check if m.checked=>"☑",ListType::Check=>"☐",ListType::Number=>"·",ListType::None=>""};self.text(p,l.editor.x+6,base,mark,t.accent,13.)}if show_line_numbers{self.text(p,l.editor.x+margin-10,base,&(i+1).to_string(),t.muted_text,10.);}self.text(p,l.editor.x+margin+14,base,line,t.text,self.font_size)}let start=s.text[..s.cursor.min(s.text.len())].rfind('\n').map_or(0,|i|i+1);let col=s.text[start..s.cursor.min(s.text.len())].chars().count();fill_rect(p,Rect::new(l.editor.x+margin+14+(col as f32*self.font_size*.62)as i32,l.editor.y+8+cursor_line as i32*lh,2,lh-4),t.accent)}
fn status(&self,p:&mut Pixmap,l:Layout,t:Theme,s:Option<&EditorSnapshot>){let track_top=l.editor.y as f32;let track_height=(l.editor.h as f32).max(1.);let total_lines=s.map_or(1,|v|v.text.split('\n').count().max(1));let visible_lines=((l.editor.h as f32)/(self.font_size*1.55).max(1.)).max(1.) as usize;let thumb_height=(track_height*(visible_lines.min(total_lines) as f32/total_lines as f32)).clamp(24f32.min(track_height),track_height);let max_scroll=total_lines.saturating_sub(visible_lines);let scroll_ratio=s.map_or(0.,|v|if max_scroll==0{0.}else{v.scroll_line.min(max_scroll)as f32/max_scroll as f32});fill_rect(p,Rect::new(l.editor.right()-7,l.editor.y,3,l.editor.h),Rgba::rgba(24,28,36,150));fill_rect(p,Rect::new(l.editor.right()-7,track_top as i32+((track_height-thumb_height)*scroll_ratio)as i32,3,thumb_height as i32),t.accent);fill_rect(p,l.status_bar,t.surface);let(location,right)=if let Some(s)=s{let pos=s.cursor.min(s.text.len());let line=s.text[..pos].bytes().filter(|b|*b==b'\n').count()+1;let start=s.text[..pos].rfind('\n').map_or(0,|i|i+1);(format!("Ln {line}, Col {}",s.text[start..pos].chars().count()+1),format!("{}  ·  {}{}",s.encoding.label(),s.line_ending.label(),if s.dirty{"  ·  Modified"}else{""}))}else{("Ln 1, Col 1".into(),"UTF-8  ·  LF".into())};self.text(p,14,l.status_bar.y+17,&location,t.text,10.5);self.text(p,l.status_bar.right()-(right.chars().count()as i32*6+20),l.status_bar.y+17,&right,t.muted_text,10.5)}
fn text(&self,p:&mut Pixmap,x:i32,baseline:i32,s:&str,c:Rgba,size:f32){let Some(font)=self.font.as_ref()else{return};let mut pen=x as f32;for ch in s.chars(){let(m,b)=font.rasterize(ch,size);let top=baseline as f32-m.ymin as f32-m.height as f32;for y in 0..m.height{for xx in 0..m.width{let a=b[y*m.width+xx];if a>0{blend(p,pen as i32+m.xmin+xx as i32,top as i32+y as i32,c,(u16::from(a)*u16::from(c.a)/255)as u8)}}}pen+=m.advance_width}}
}
fn load_font()->Option<Font>{[std::env::var_os("NOTEPAD_PRO_FONT").map(std::path::PathBuf::from),Some(Path::new("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf").into()),Some(Path::new("C:\\Windows\\Fonts\\consola.ttf").into()),Some(Path::new("/System/Library/Fonts/Menlo.ttc").into())].into_iter().flatten().find_map(|p|Font::from_bytes(std::fs::read(p).ok()?,FontSettings::default()).ok())}
fn colour(c:LineColour)->Rgba{let v=c.rgb().unwrap_or(0);Rgba::rgb((v>>16)as u8,(v>>8)as u8,v as u8)}fn fill_rect(p:&mut Pixmap,r:Rect,c:Rgba){if r.w<=0||r.h<=0{return}let mut b=PathBuilder::new();b.move_to(r.x as f32,r.y as f32);b.line_to(r.right()as f32,r.y as f32);b.line_to(r.right()as f32,r.bottom()as f32);b.line_to(r.x as f32,r.bottom()as f32);b.close();if let Some(path)=b.finish(){let mut paint=tiny_skia::Paint::default();paint.set_color(Color::from_rgba8(c.r,c.g,c.b,c.a));p.fill_path(&path,&paint,FillRule::Winding,Transform::identity(),None)}}fn fill_circle(p:&mut Pixmap,x:f32,y:f32,r:f32,c:Rgba){let mut b=PathBuilder::new();b.push_circle(x,y,r);if let Some(path)=b.finish(){let mut paint=tiny_skia::Paint::default();paint.set_color(Color::from_rgba8(c.r,c.g,c.b,c.a));p.fill_path(&path,&paint,FillRule::Winding,Transform::identity(),None)}}fn blend(p:&mut Pixmap,x:i32,y:i32,c:Rgba,a:u8){if x<0||y<0||x>=p.width()as i32||y>=p.height()as i32{return}let i=(y as usize*p.width()as usize+x as usize)*4;let d=p.data_mut();let inv=255-u16::from(a);d[i]=((u16::from(c.r)*u16::from(a)+u16::from(d[i])*inv)/255)as u8;d[i+1]=((u16::from(c.g)*u16::from(a)+u16::from(d[i+1])*inv)/255)as u8;d[i+2]=((u16::from(c.b)*u16::from(a)+u16::from(d[i+2])*inv)/255)as u8;d[i+3]=a.max(d[i+3])}
